spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: springcloud-config-dept8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 2019
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


# Eureka配置
eureka:
  client:
    #"defaultZone", "http://localhost:8761/eureka/"
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 默认描述信息
    instance-id: springcloud-provider-dept8001
# 配置服务信息
info:
  app.name: Aaron-springcloud
  company.name: blod.Aaron.com
  
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: springcloud-config-dept8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 2019
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# Eureka配置
eureka:
  client:
    #"defaultZone", "http://localhost:8761/eureka/"
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    # 默认描述信息
    instance-id: springcloud-provider-dept8001
# 配置服务信息
info:
  app.name: Aaron-springcloud
  company.name: blod.Aaron.com

